### ISSUE TITLE
[Error]: 0 enemies targeted by 653:NPC_EARTHQUAKE, divide per 0 avoided!

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1679]
Mode: Pre-Renewal
Git Hash: Latest
Bug: Core / Skill
Issue:
In the process of killing Maya Purple or Maya you will get this message:
[Error]: 0 enemies targeted by 653:NPC_EARTHQUAKE, divide per 0 avoided!

**Comment by Akkarinage** [comment]
Referencing #1362

**Comment by keitenai** [comment]
![capture](https://cloud.githubusercontent.com/assets/11855571/19932816/97756d38-a0ce-11e6-9c6c-73e87d3f0fe8.PNG)

got same bug

**Comment by aleos89** [comment]
Can you explain the situation the error came about? The error doesn't really provide any info on how to reproduce it.

**Comment by keitenai** [comment]
I'm trying to reproduce this but i'm still unable to.
I'll report it once we find the way.

**Comment by Playtester** [comment]
When it previously appeared it was either:
1. At end of cast time nobody was on screen to be hit by the skill.
2. All targets dodged the attack.

But I thought both issues were fixed by now. Can you check if one of the two situations causes the error?

**Comment by CairoLee** [comment]
Try this reproduction step:

When the mob start casting NPC_EARTHQUAKE, before the cast finish, move the player to leave the mob‘s optic angle(@speed 1 or @jump).

**Comment by keitenai** [comment]
It was caused by an MVP attacking many assassin crosses that keep avoiding magic via backslide.

**Comment by srhmike** [comment]
Git: 8492f6c
Can confirm this is still happening. With my server its happening when they are in my MvP rooms, I believe that the skill is missing the player, because they are right next to it when it happens.  I believe it was turtle general using the skill.

**Comment by TheNoobCompany** [comment]
I can confirm on pre-renewal as well (as a player)

EQ from ifrit/Orc Lord deals 0 damages to me when I'm close to him, and only deals damage when I seems to be max range from it.

Client: 2013-08-07
Git: c87dba5a52594772a6fbdbbff209bef0e22e85a7

**Comment by Anjuts** [comment]
This still happening

**Comment by darking12345** [comment]
I can confirm the issue still happening

 0 enemies targeted by 653:NPC_EARTHQUAKE, divide per 0 avoided!

not sure how to reproduce
