### ISSUE TITLE
MO_FINGEROFFENSIVE Lv2+ doesnt work as it should be

### ISSUE THREAD

**Issue by qwerty7vp** [rathena/rathena#4863]
* **rAthena Hash**: 4829f3775

* **Client Date**: 20180919Ragexe, 20180620RagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: All level damage almost the same and only 1 hit
  * Expected Result: Hit and Damage should raise according to skill level
  * How to Reproduce: Create Sura/Champion character and test the skill
  * Official Information:
  

Video for my testing : https://youtu.be/-p40Qx2_Dow

* **Modifications that may affect results**: Nothing I tried set finger_offensive_type: both 0 and 1 and `@reloadbattleconf` , `@reloadskilldb`
`

**Comment by Daegaladh** [comment]
I already fixed this on 38cf16edbaa36836072780b4481023e57e014892
I've just tested it on a clean rAthena and works fine, setting `finger_offensive_type` to 0 hits depending on the number of spheres you have, and setting it to 1 does all the damage in 1 hit.

**Comment by qwerty7vp** [comment]
but I'm using latest rA and it has your fix but it still hit only once with both setting to 0 and 1
![image](https://user-images.githubusercontent.com/64515036/80631811-7ca73000-8a80-11ea-869d-4b98180e86c6.png)

**Comment by Daegaladh** [comment]
You must be doing something wrong
https://i.imgur.com/rkb3nNB.mp4

**Comment by qwerty7vp** [comment]
what's diff client and kRO version you're using ?
I tried to clone clean latest rathena 2 minutes ago
it's still not working like yours

**Comment by Daegaladh** [comment]
I've tested both on 2018-06-21aRagexe and 2015-05-13aRagexe
But I don't think it's something related to the client

**Comment by qwerty7vp** [comment]
this is weird I tried many things
2019 kRO , 2020 kRO
20180620RagexeRE, 20180621Ragexe/RagexeRE, 20180919Ragexe
with clean latest rA ( only conf/import folder that edited)
still cant make it multihit
is there a condition of the skill to make it multihit ? like weapon or buff or something ?

**Comment by Daegaladh** [comment]
The only condition is the spheres, the hits depend on the number of spheres you have
